"""init

Revision ID: b39fb3f8c07b
Revises:
Create Date: 2026-07-23 15:47:01.486090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b39fb3f8c07b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=500), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('api', 'scraper', 'csv')", name="ck_competitor_source_type"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_extracted", sa.Integer(), nullable=False),
        sa.Column("records_validated", sa.Integer(), nullable=False),
        sa.Column("records_stored", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column(
            "error_details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed')", name="ck_pipeline_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("brand", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_brand"), "products", ["brand"], unique=False)
    op.create_index(
        op.f("ix_products_category"), "products", ["category"], unique=False
    )
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_table(
        "price_changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("competitor_id", sa.UUID(), nullable=False),
        sa.Column("old_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("new_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("price_diff", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("pct_change", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "change_type IN ('drop', 'increase')", name="ck_change_type"
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"], ["competitors.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_price_changes_type_date",
        "price_changes",
        ["change_type", "detected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_changes_detected_at"),
        "price_changes",
        ["detected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_changes_product_id"),
        "price_changes",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "price_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("competitor_id", sa.UUID(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("original_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("in_stock", sa.Boolean(), nullable=False),
        sa.Column(
            "scraped_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_run_id", sa.String(length=100), nullable=True),
        sa.CheckConstraint("price >= 0", name="ck_price_positive"),
        sa.ForeignKeyConstraint(
            ["competitor_id"], ["competitors.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "competitor_id", "scraped_at", name="uq_price_observation"
        ),
    )
    op.create_index(
        "idx_price_records_latest",
        "price_records",
        ["product_id", "competitor_id", "scraped_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_records_competitor_id"),
        "price_records",
        ["competitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_records_product_id"),
        "price_records",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_records_scraped_at"),
        "price_records",
        ["scraped_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_records_source_run_id"),
        "price_records",
        ["source_run_id"],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("price_change_id", sa.UUID(), nullable=True),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name="ck_alert_severity",
        ),
        sa.ForeignKeyConstraint(
            ["price_change_id"], ["price_changes.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alerts_unacked", "alerts", ["is_acknowledged", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_alerts_unacked", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_price_records_source_run_id"), table_name="price_records")
    op.drop_index(op.f("ix_price_records_scraped_at"), table_name="price_records")
    op.drop_index(op.f("ix_price_records_product_id"), table_name="price_records")
    op.drop_index(op.f("ix_price_records_competitor_id"), table_name="price_records")
    op.drop_index("idx_price_records_latest", table_name="price_records")
    op.drop_table("price_records")
    op.drop_index(op.f("ix_price_changes_product_id"), table_name="price_changes")
    op.drop_index(op.f("ix_price_changes_detected_at"), table_name="price_changes")
    op.drop_index("idx_price_changes_type_date", table_name="price_changes")
    op.drop_table("price_changes")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_index(op.f("ix_products_brand"), table_name="products")
    op.drop_table("products")
    op.drop_table("pipeline_runs")
    op.drop_table("competitors")
    # ### end Alembic commands ###
